### ISSUE TITLE
Latest fix for pages made only two pages available in one category.

### ISSUE THREAD

**Issue by enceos** [obivandamme/Workshop#26]
After the latest fix for workshop category pages, which reverts categories to the first page after switching between them, I have only 2 pages in my category menus. Usually Utitlity and Structural categories have 5 pages on my install. "Next Page" button for pages 3 and further appears only after closing and reopening the UI.

**Comment by NyankoSensei** [comment]
This bug still again, main category work with all pages but if you switch category you get only 2 pages

**Comment by obivandamme** [comment]
Are you sure there is a missing part? The categories are shorter for the simple reason of them being filtered. The ALL category will be gone in one of the next updates because it is way to large and contains items, that should not be printable. Please provide me with the name of a stock part, that is available in the ALL category, but is missing when filtered, so that I can reproduce and fix this

**Comment by NyankoSensei** [comment]
For what i can see when i open workshop windows i get all the pages in the main category, if i change category i get only 2 pages and if i go back to the main i get again 2 pages, i have to close and open workshop windows for get all the pages again
